package eu.gigu979.risk.process.test.suite;

import java.io.IOException;
import java.util.Map;

import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.CloseableHttpClient;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

import eu.gigu979.risk.process.test.model.ApiResponse;
import eu.gigu979.risk.process.test.model.ProcessModelDto;
import eu.gigu979.risk.process.test.model.ProcessRequestDto;
import eu.gigu979.risk.process.test.utils.AssertUtils;
import eu.gigu979.risk.process.test.utils.ClientUtils;
import eu.gigu979.risk.process.test.utils.ConfigUtils;
import eu.gigu979.risk.process.test.utils.DBUtils;
import eu.gigu979.risk.process.test.utils.TestUtils;

/**
 * Test suite for verifying successful process creation and data integrity
 * across API responses and Teradata persistence.
 */
public class ProcessApiSuccessSuite {

	private CloseableHttpClient httpClient;

	@BeforeEach
	void setUp() {
		httpClient = ClientUtils.createDefaultClient();
	}

	@AfterEach
	void tearDown() throws IOException {
		if (httpClient != null) {
			httpClient.close();
		}
	}

	@Test
	@DisplayName("Test Success: Process Creation and API + DB Data Integrity Verification")
	void testCreateProcess_Success() throws Exception {
		// 1. Setup DTO with unique data to avoid collisions
		String uniqueName = "PROC_TEST_" + System.currentTimeMillis();
		ProcessRequestDto requestDto = TestUtils.createValidDto();
		requestDto.setName(uniqueName);

		// 2. Execute API POST request
		HttpPost request = ClientUtils.createPostRequest(requestDto);

		try (CloseableHttpResponse response = httpClient.execute(request)) {

			// 3. Analyze and validate API response
			ApiResponse<ProcessModelDto> apiResponse = TestUtils.<ProcessModelDto>parseResponse(response);

			// Verify status code and absence of business errors
			AssertUtils.assertSuccess(response, apiResponse);

			// Verify that the response body contains the expected data
			ProcessModelDto responseDto = apiResponse.getData();
			Assertions.assertNotNull(responseDto, "The 'data' field in the API response is null");
			Assertions.assertEquals(uniqueName, responseDto.getName(), "The returned name does not match the sent name");
			Assertions.assertNotNull(responseDto.getId(), "The ID generated by the API is null");

			// 4. Verify persistence on Teradata via Spring JDBC
			verifyDatabaseState(uniqueName, requestDto);
		}
	}

	/**
	 * Internal method for Teradata DB verification. * @param name The unique name
	 * used to look up the record.
	 * 
	 * @param expected The original request data for comparison.
	 * @throws ClassNotFoundException 
	 */
	private void verifyDatabaseState(String name, ProcessRequestDto expected) throws ClassNotFoundException {
		JdbcTemplate jdbc = DBUtils.getJdbcTemplate();
		String sql = ConfigUtils.getQuery("event.find.last.by.name");

		// Fetch record (Throws exception if not found)
		Map<String, Object> dbRow = jdbc.queryForMap(sql, name);

		// Assertions on physical data
		Assertions.assertFalse(dbRow.isEmpty(), "Record not found in table T_EVENT");
		Assertions.assertEquals(name, dbRow.get("EVENT_NAME"), "Incorrect EVENT_NAME in DB");

		// Verify timestamp presence (handle conversion if necessary)
		Assertions.assertNotNull(dbRow.get("CREATE_TIMESTAMP"), "CREATE_TIMESTAMP missing in DB");

		System.out.println("Teradata verification successful for Record ID: " + dbRow.get("ID_EVENT"));
	}
}